###
GET http://localhost:8100/pg/payment/detailByToken/5ad32ab402624594ba521814dde5a859
Accept: */*
Cache-Control: no-cache

###
GET http://localhost:8100/pg/payment/cancel/5ad32ab402624594ba521814dde5a859
Accept: */*
Cache-Control: no-cache

###
POST http://localhost:8100/pg/payment/checkout
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "token": "406e5b2dea16468ab9331917f77e30c4",
  "paymentMode": "PW"
}

