###
GET http://localhost:8100/pg/payment/detailByToken/d48d7d239b6143c2bc7f2fa0d3b322e3
Accept: */*
Cache-Control: no-cache

###
GET http://localhost:8100/pg/payment/cancel/d48d7d239b6143c2bc7f2fa0d3b322e3
Accept: */*
Cache-Control: no-cache

###
GET http://localhost:8100/pg/payment/status/d48d7d239b6143c2bc7f2fa0d3b322e3
Accept: */*
Cache-Control: no-cache

###
POST http://localhost:8100/pg/payment/checkout
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "token": "d48d7d239b6143c2bc7f2fa0d3b322e3",
  "paymentMode": "PW"
}

