/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.alibaba.dts.formats.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Long extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7898167995154910628L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Long\",\"namespace\":\"com.alibaba.dts.formats.avro\",\"fields\":[{\"name\":\"precision\",\"type\":\"long\"},{\"name\":\"value\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Long> ENCODER =
      new BinaryMessageEncoder<Long>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Long> DECODER =
      new BinaryMessageDecoder<Long>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Long> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Long> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Long>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Long to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Long from a ByteBuffer. */
  public static Long fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long precision;
  @Deprecated public java.lang.String value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Long() {}

  /**
   * All-args constructor.
   * @param precision The new value for precision
   * @param value The new value for value
   */
  public Long(java.lang.Long precision, java.lang.String value) {
    this.precision = precision;
    this.value = value;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return precision;
    case 1: return value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: precision = (java.lang.Long)value$; break;
    case 1: value = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'precision' field.
   * @return The value of the 'precision' field.
   */
  public java.lang.Long getPrecision() {
    return precision;
  }

  /**
   * Sets the value of the 'precision' field.
   * @param value the value to set.
   */
  public void setPrecision(java.lang.Long value) {
    this.precision = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the 'value' field.
   */
  public java.lang.String getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.String value) {
    this.value = value;
  }

  /**
   * Creates a new Long RecordBuilder.
   * @return A new Long RecordBuilder
   */
  public static com.alibaba.dts.formats.avro.Long.Builder newBuilder() {
    return new com.alibaba.dts.formats.avro.Long.Builder();
  }

  /**
   * Creates a new Long RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Long RecordBuilder
   */
  public static com.alibaba.dts.formats.avro.Long.Builder newBuilder(com.alibaba.dts.formats.avro.Long.Builder other) {
    return new com.alibaba.dts.formats.avro.Long.Builder(other);
  }

  /**
   * Creates a new Long RecordBuilder by copying an existing Long instance.
   * @param other The existing instance to copy.
   * @return A new Long RecordBuilder
   */
  public static com.alibaba.dts.formats.avro.Long.Builder newBuilder(com.alibaba.dts.formats.avro.Long other) {
    return new com.alibaba.dts.formats.avro.Long.Builder(other);
  }

  /**
   * RecordBuilder for Long instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Long>
    implements org.apache.avro.data.RecordBuilder<Long> {

    private long precision;
    private java.lang.String value;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.alibaba.dts.formats.avro.Long.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.precision)) {
        this.precision = data().deepCopy(fields()[0].schema(), other.precision);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Long instance
     * @param other The existing instance to copy.
     */
    private Builder(com.alibaba.dts.formats.avro.Long other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.precision)) {
        this.precision = data().deepCopy(fields()[0].schema(), other.precision);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'precision' field.
      * @return The value.
      */
    public java.lang.Long getPrecision() {
      return precision;
    }

    /**
      * Sets the value of the 'precision' field.
      * @param value The value of 'precision'.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Long.Builder setPrecision(long value) {
      validate(fields()[0], value);
      this.precision = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'precision' field has been set.
      * @return True if the 'precision' field has been set, false otherwise.
      */
    public boolean hasPrecision() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'precision' field.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Long.Builder clearPrecision() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public java.lang.String getValue() {
      return value;
    }

    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Long.Builder setValue(java.lang.String value) {
      validate(fields()[1], value);
      this.value = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Long.Builder clearValue() {
      value = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Long build() {
      try {
        Long record = new Long();
        record.precision = fieldSetFlags()[0] ? this.precision : (java.lang.Long) defaultValue(fields()[0]);
        record.value = fieldSetFlags()[1] ? this.value : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Long>
    WRITER$ = (org.apache.avro.io.DatumWriter<Long>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Long>
    READER$ = (org.apache.avro.io.DatumReader<Long>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
