
###{% client.global.set("orgId", 10); %}

###
GET http://localhost:8200/uc/company/findByOrgIds?namespace=sms&orgIds=1,3,5,6
Accept: */*
Cache-Control: no-cache

###
PUT http://localhost:8200/uc/company/setting/2
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "name": "org name xxx",
  "logo": "onionwallet:/img/20191213/870576fc-025b-6862-ca5d-aa2f2f72f88f.jpg"
}

###
PUT http://localhost:8200/uc/company/setting/1/sms
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "signature": "RupeeWallet",
  "senderNum": "RUPEEW",
  "brand": "RupeeWallet",
  "supplier": {
    "skyline" : {
      "signature": "RupeeWallet",
      "senderNum": "RUPEEW",
      "brand": "RupeeWallet",
      "appId": "cs_3wegkt",
      "appSecret": "dwhg27jN",
      "sendUrl" : "http://sms.skylinelabs.cc:20003/"
    }
  }
}
###"brand": "RupeeWallet",

###
PUT http://localhost:8200/uc/company/setting/1/pay
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "returnUrl": "https://h5.onionwallet.net/payment/result/",
  "supplier": {
    "dokypay" : {
      "appId": "1001412384",
      "appSecret": "bc2d5fc0c8d2442d86c9f4fd2d4a0b6b",
      "version": "1.1",
      "createUrl": "https://gatewaybeta.dokypay.com/clientapi/unifiedorder",
      "returnUrl": "https://h5.onionwallet.net/payment/result/",
      "notifyUrl" : "https://onionwallet.net/api/pay/dokypay/subscrib"
    },
    "cashfree": {
      "appId": "17713c62431585d3ed8c5edbe31771",
      "appSecret": "69c81cb73a931bb5d7fe301f80b27e15b74089e2",
      "version": "",
      "createUrl": "https://test.cashfree.com/api/v1/order/create",
      "returnUrl": "https://h5.onionwallet.net/payment/result/handler",
      "notifyUrl" : "https://onionwallet.net/api/pay/cashfree/subscribe"
    }
  }
}

