


###
POST http://localhost:8100/loan/confirm
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "goodsId" : 1
}

> {%
client.global.set("tradeNo", response.body.data.tradeNo);
%}

###
PUT http://localhost:8100/loan/dev/approve/{{tradeNo}}
Accept: */*
Cache-Control: no-cache

###
PUT http://localhost:8100/loan/dev/loaning/{{tradeNo}}
Accept: */*
Cache-Control: no-cache


###
PUT http://localhost:8100/loan/dev/loaned
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "tradeNo": "{{tradeNo}}",
  "effectAt": "2020-03-01"
}

###
GET http://localhost:8100/loan/{{tradeNo}}?lang=zh_CN
Accept: */*
Cache-Control: no-cache

###