GET http://localhost:9100/daily/koi
Accept: */*
Cache-Control: no-cache


###
GET http://localhost:9100/daily/trade
Accept: */*
Cache-Control: no-cache

###
GET http://127.0.0.1:9100/daily/koi/audit
Accept: */*
Cache-Control: no-cache

###