GET http://localhost:9100/index/contract
Accept: */*
Cache-Control: no-cache


###
GET http://localhost:9100/index/jdbc
Accept: */*
Cache-Control: no-cache

###
GET http://localhost:9100/index/mail/hello
Accept: */*
Cache-Control: no-cache