POST http://localhost:8100/auth/sms/registerAndLogin
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "mobile": "18067966015",
  "code": "778899",
  "orgId": 1
}

###
POST http://localhost:8100/auth/sms/code
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "mobile": "18067966015",
  "orgId": 1
}

###
POST http://localhost:8100/auth/logout
Accept: */*
Cache-Control: no-cache
Content-Type: application/json


###
POST http://localhost:8100/account/show
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###
POST http://localhost:8100/auth/password/register
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "account": "18067966016",
  "password": "123456",
  "orgId": 1
}


###
POST http://localhost:8100/auth/password/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "account": "18067966016",
  "password": "123456",
  "orgId": 1
}


###
POST http://localhost:8100/auth/password/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "account": "18067966016",
  "password": "abcdef",
  "orgId": 1
}

###
POST http://localhost:8100/auth/password/registerAndLogin
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "account": "18067966016",
  "password": "abcdef",
  "orgId": 1
}


###
POST http://localhost:8100/auth/password/change
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "account": "18067966016",
  "password": "123456",
  "newPassword": "abcdef",
  "orgId": 1
}

###
###
PUT http://localhost:8100/auth/company/change/3
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###