# hello world
POST http://localhost:8100/pay/razorpay/subscribe
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
X-Razorpay-Event-Id: EbF7N2ZFbCZbq5
X-Razorpay-Signature: 1b98df9b329b117623827355889059fe565592b717847d928d2c0435745e3027

{"entity":"event","account_id":"acc_EKXMRHi2Y72UvU","event":"payout.processed","contains":["payout"],"payload":{"payout":{"entity":{"id":"pout_EbEza6CNgdZghU","entity":"payout","fund_account_id":"fa_EbEzPC9IMQQs3P","amount":90000,"currency":"INR","notes":[],"fees":472,"tax":72,"status":"processed","purpose":"payout","utr":"EbEza6CNgdZghU","mode":"IMPS","reference_id":"20200406225634600199647934535939","narration":"onion Fund Transfer","batch_id":null,"failure_reason":null,"created_at":1586184996}}},"created_at":1586185438}


###
POST http://localhost:8100/pay/dokypay/subscribe
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded

processCurrency=INR&amount=100.00&merTransNo=20200610182608601389643149994897&sign=17cf5db15d66bf3caee6c44e282cc6f8427581f82557668e1b49687de07ecb98&updateTime=2020-06-10+18%3A26%3A17&pmId=credit.in&transNo=20200610182609169010479049&payerMobile=917338198975&createTime=2020-06-10+18%3A26%3A09&processAmount=100.00&payerName=widh+che+gaga&currency=INR&payerEmail=wibdj%40gmai.com&transStatus=success

###
POST http://localhost:8100/pay/cashfree/subscribe
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded

orderId=20200609234929601209421149923896&orderAmount=100.00&referenceId=356976&txStatus=SUCCESS&paymentMode=CREDIT_CARD&txMsg=Transaction+Successful&txTime=2020-06-09+21%3A20%3A12&signature=tfwE01vFLd5W8Pr2%2Bfwg6jIuHoR%2F8Cs9Sxr3eshoTnY%3D


###
POST http://localhost:8100/pay/dLocal/subscribe
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"id":"D-155168-f568e7a2-079a-45cd-ac8c-ee136eee474d","amount":100.00,"status":"PAID","status_detail":"The payment was paid.","status_code":"200","currency":"INR","country":"IN","payment_method_id":"PW","payment_method_type":"BANK_TRANSFER","payment_method_flow":"REDIRECT","payer":{"name":"Rajesh Koothrappali","user_reference":"DL_NOT_PROVIDED_846168","email":"rajesh@acme.com","phone":"7338198975","document":"EHFGA5967A","address":{"city":"Goa","street":"Maddo Vaddo","empty":false}},"order_id":"20200707162535000189401265885689","notification_url":"https://onionwallet.net/api/pay/dLocal/subscribe","callback_url":"http://sandbox.onionwallet.net/result/a2897faafa514d9da4d3a35665d691e6","created_date":"2020-07-07T08:26:08.000+0000"}


