


### 支付单列表
GET http://localhost:8200/pay/payment/query?payeeId=80
Accept: */*
Cache-Control: no-cache

### 流水列表
GET http://localhost:8200/pay/transaction/query?pageSize=20&pageNum=1
Accept: */*
Cache-Control: no-cache


### 结算列表
GET http://localhost:8200/pay/settlement/query
Accept: */*
Cache-Control: no-cache


### 结算列表
GET http://localhost:8200/pay/payment/detail/20220524105347600809139026570886
Accept: */*
Cache-Control: no-cache


###
POST http://localhost:8200/pay/payment/batchSuccess
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "noList": [
    "20210928124444695779873222170281",
    "20210928124308691089096222159398"
  ]
}

###
POST http://localhost:8200/pay/payment/query
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "utrList": [
    "207014403483",
    "207321608741",
    "206019460199",
    "206042305839"
  ]
}