GET http://localhost:9000/auth/sms/registerAndLogin?mobile=18067966015&code=648858&orgId=1
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:9000/auth/sms/code?mobile=18067966015
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:9000/auth/logout
Accept: */*
Cache-Control: no-cache

###
GET http://localhost:9000/account/show
Accept: */*
Cache-Control: no-cache

###