POST http://localhost:9000/auth/sms/registerAndLogin
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "mobile": "18067966015",
  "code": "123",
  "orgId": 1
}

###
POST http://localhost:9000/auth/sms/code
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "mobile": "919740030986",
  "orgId": 1
}


###
POST http://localhost:9000/auth/sms/code?lang=en_US
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "mobile": "+919740030986",
  "orgId": 1
}





###
POST http://localhost:9000/auth/logout
Accept: */*
Cache-Control: no-cache
Content-Type: application/json


###
POST http://localhost:9000/account/show
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###
POST http://localhost:9000/auth/password/register
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "account": "18067966016",
  "password": "123456",
  "orgId": 1
}


###
POST http://localhost:9000/auth/password/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "account": "18067966016",
  "password": "123456",
  "orgId": 1
}


###
POST http://localhost:9000/auth/password/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "account": "18067966016",
  "password": "abcdef",
  "orgId": 1
}

###
POST http://localhost:9000/auth/password/registerAndLogin
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "account": "18067966016",
  "password": "abcdef",
  "orgId": 1
}


###
POST http://localhost:9000/auth/password/change
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "account": "18067966016",
  "password": "123456",
  "newPassword": "abcdef",
  "orgId": 1
}

###
GET http://localhost:9000/auth/lang?lang=zh-CN
Accept: */*
Cache-Control: no-cache

###
GET http://localhost:9000/auth/lang?lang=en-US
Accept: */*
Cache-Control: no-cache

###