
###{% client.global.set("orgId", 10); %}

###
GET http://localhost:8200/uc/company/findByOrgIds?namespace=sms&orgIds=1,3,5,6
Accept: */*
Cache-Control: no-cache

###
PUT http://localhost:8200/uc/company/setting/32
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "name": "org name xxx",
  "logo": "onionwallet:/img/20191213/870576fc-025b-6862-ca5d-aa2f2f72f88f.jpg"
}

###
PUT http://localhost:8200/uc/company/setting/1/sms
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "signature": "RupeeWallet",
  "senderNum": "RUPEEW",
  "brand": "RupeeWallet",
  "supplier": {
    "skyline" : {
      "signature": "RupeeWallet",
      "senderNum": "RUPEEW",
      "brand": "test",
      "appId": "cs_3wegkt",
      "appSecret": "dwhg27jN",
      "sendUrl" : "http://sms.skylinelabs.cc:20003/"
    }
  }
}
###"brand": "RupeeWallet",
