


###
POST http://localhost:8100/loan/preview
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "goodsId" : 1
}

###
POST http://localhost:8100/loan/confirm
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "goodsId" : 15
}



###
#PUT http://localhost:8100/loan/repay/installment
#Accept: */*
#Cache-Control: no-cache
#Content-Type: application/json
#
#{
#  "tradeNo" : "20200303195344000119344411981847",
#  "installmentNo": 1
#}

###
GET http://localhost:8100/loan/20200406233201000209141440380805?lang=zh_CN
Accept: */*
Cache-Control: no-cache


###
GET http://localhost:8100/loan
Accept: */*
Cache-Control: no-cache

###
GET http://localhost:8100/loan?pageNum=10
Accept: */*
Cache-Control: no-cache

###
GET http://localhost:8100/loan/living
Accept: */*
Cache-Control: no-cache


###


###
PUT http://localhost:8100/loan/repay
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "tradeNo" : "20200303204857000119453125198010",
  "installmentNo": 1
}

###