# hello world
POST http://localhost:8100/pay/razorpay/subscribe
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
X-Razorpay-Event-Id: idxxx
X-Razorpay-Signature: signxxx


{
  "entity": "event",
  "account_id": "acc_EKXMRHi2Y72UvU",
  "event": "order.paid",
  "contains": [
    "payment",
    "order"
  ],
  "payload": {
    "payment": {
      "entity": {
        "id": "pay_EOXyyZkhOsSIzH",
        "entity": "payment",
        "amount": 38660,
        "currency": "INR",
        "status": "captured",
        "order_id": "order_EOXyh0J9roM6OM",
        "invoice_id": null,
        "international": false,
        "method": "upi",
        "amount_refunded": 0,
        "refund_status": null,
        "captured": true,
        "description": "Credits towards consultation",
        "card_id": null,
        "bank": null,
        "wallet": null,
        "vpa": "uuuu@paytm",
        "email": "gaurav.kumar@example.com",
        "contact": "+919191919191",
        "notes": [],
        "fee": 914,
        "tax": 140,
        "error_code": null,
        "error_description": null,
        "created_at": 1583413451
      }
    },
    "order": {
      "entity": {
        "id": "order_EOXyh0J9roM6OM",
        "entity": "order",
        "amount": 38660,
        "amount_paid": 38660,
        "amount_due": 0,
        "currency": "INR",
        "receipt": "20200305210354600059505955474084",
        "offer_id": null,
        "status": "paid",
        "attempts": 1,
        "notes": [],
        "created_at": 1583413434
      }
    }
  },
  "created_at": 1583413451
}

###

# test
POST https://onionwallet.net/api/pay/razorpay/subscribe
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "name": "ok",
  "tradeNo" : "20200303195344000119344411981847",
  "installmentNo": 1
}

###


