



### loan goods create
POST http://localhost:8200/goods
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "name": "pay test",
  "price": 1000,
  "loan" : {
     "handlingFeeRate": 10,
     "period": 15,
     "interest":1,
     "penalty": 2
  },
  "installmentList": [
     {
       "period": 5,
       "percentage":33,
       "feePercentage":33,
       "type":10
     }, {
       "period": 5,
       "percentage":33,
       "feePercentage":33,
       "type":10
     }, {
       "period": 5,
       "percentage":33,
       "feePercentage":33,
       "type":10
     }
  ]
}

### goods edit
PUT http://localhost:8200/goods
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "id" : 1,
  "name": "loan changed name",
  "price": 2000,
  "loan" : {
    "handlingFeeRate": 10,
    "period": 15,
    "interest":1,
    "penalty": 2
  },
  "installmentList": [
    {
      "period": 5,
      "percentage":33,
      "feePercentage":33,
      "type":10
    }, {
      "period": 5,
      "percentage":33,
      "feePercentage":33,
      "type":10
    }, {
      "period": 5,
      "percentage":33,
      "feePercentage":33,
      "type":10
    }
  ]
}

###
DELETE http://localhost:8200/goods/2
Accept: */*
Cache-Control: no-cache

###
GET http://localhost:8200/goods/one
Accept: */*
Cache-Control: no-cache

###
GET http://localhost:8200/goods/1
Accept: */*
Cache-Control: no-cache


###
PUT http://localhost:8200/goods/listing/1
Accept: */*
Cache-Control: no-cache

###
PUT http://localhost:8200/goods/delisting/1
Accept: */*
Cache-Control: no-cache

###
GET http://localhost:8200/goods
Accept: */*
Cache-Control: no-cache

###
GET http://localhost:8200/goods?pageNum=1
Accept: */*
Cache-Control: no-cache

###

### loan goods create
POST http://localhost:8200/goods
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "name": "audit fee test",
  "price": 100,
  "goodsType": 61
}

###
GET http://localhost:8200/goods/one?goodsType=61
Accept: */*
Cache-Control: no-cache

###
