### 借款合同详情
GET http://localhost:8200/loan/contract/20200303204857000119453125198010
Accept: */*
Cache-Control: no-cache

### 商家合同列表
GET http://localhost:8200/loan/contract?pageNum=2
Accept: */*
Cache-Control: no-cache

### 买家固定店铺合同列表
GET http://localhost:8200/loan/contract/buyer?buyerId=11&pageNum=1
Accept: */*
Cache-Control: no-cache

### 商家待审核列表
GET http://localhost:8200/loan/contract/waitToApprove?pageNum=2
Accept: */*
Cache-Control: no-cache

### 商家待放款列表
GET http://localhost:8200/loan/contract/loaning?pageNum=2
Accept: */*
Cache-Control: no-cache

### 商家已审核列表
GET http://localhost:8200/loan/contract/approved?pageNum=2
Accept: */*
Cache-Control: no-cache

### 商家已打款列表
GET http://localhost:8200/loan/contract/waitToRepay?pageNum=2
Accept: */*
Cache-Control: no-cache

### 商家当天到期列表
GET http://localhost:8200/loan/contract/due?pageNum=2
Accept: */*
Cache-Control: no-cache

### 商家当天逾期列表
GET http://localhost:8200/loan/contract/overdue?pageNum=2
Accept: */*
Cache-Control: no-cache

### 买家在指定店铺逾期列表
GET http://localhost:8200/loan/contract/overdue/10?pageNum=2
Accept: */*
Cache-Control: no-cache

### 通过借款请求
PUT http://localhost:8200/loan/contract/approve/20200324185310000119392273169088
Accept: */*
Cache-Control: no-cache

### 拒绝借款请求
PUT http://localhost:8200/loan/contract/refuse/20200201182540000039040260868492
Accept: */*
Cache-Control: no-cache

### 放款
PUT http://localhost:8200/loan/contract/loan/20200324185310000119392273169088
Accept: */*
Cache-Control: no-cache

###
GET http://localhost:8200/loan/contract/20200323225602000119529981693243?lang=en_US
Accept: */*
Cache-Control: no-cache


### 买家固定店铺合同列表
GET http://localhost:8200/loan/contract/buyer?buyerId=3&pageNum=1
Accept: */*
Cache-Control: no-cache

###