
###  create collection
POST http://localhost:8200/task/collection
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "name" : "collection task",
  "memo" : "collection task memo",
  "tags" : "test, dev",
  "projectId" : 1,
  "trade" : {
    "tradeNo" : "abc123456",
    "tradeType": 2,
    "installmentNo": 1,
    "currency" : 101,
    "amount" : 1200.00,
    "interestRate": 0.01,
    "dueAt" : "2020-02-10"
  }
}


###  create contact
POST http://localhost:8200/task/contact
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "parentId" : 1,
  "staffId": 10,
  "name" : "contact customer",
  "memo" : "customer contact memo",
  "tags" : "test, dev",
  "contact" : {
    "partnerOrgId" : 1,
    "customerId" : 10,
    "contactPerson" : 1,
    "contactMethod" : 1,
    "contactState" : 1,
    "contactResult" : 1,

    "contactAttachment" : "/yyy/xxx.jpg",
    "resultAttachment" : "/result/att.jpg",
    "recontactAt" : "2020-03-20T09:30:00"
  }
}

###
GET http://localhost:8200/task/task/1
Accept: */*
Cache-Control: no-cache

###
GET http://localhost:8200/task/collection/1
Accept: */*
Cache-Control: no-cache

###
GET http://localhost:8200/task/contact/21
Accept: */*
Cache-Control: no-cache

### task assign
PUT http://localhost:8200/task/assign
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "staffId": 10,
  "taskId": 1
}

###  task assign
PUT http://localhost:8200/task/assign
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "staffId": 10,
  "taskIds": [1, 3, 5]
}

### TODO update amount
PUT http://localhost:8200/task/collection/partlyPay/1/100
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

### TODO update amount
PUT http://localhost:8200/task/collection/confirm/partlyPay/1/100
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###
PUT http://localhost:8200/task/collection/pay/1
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###
PUT http://localhost:8200/task/collection/confirm/pay/1
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###
PUT http://localhost:8200/task/collection/fail/1
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###
PUT http://localhost:8200/task/collection/confirm/fail/1
Accept: */*
Cache-Control: no-cache
Content-Type: application/json


###
GET http://localhost:8200/task/all?pageNum=3
Accept: */*
Cache-Control: no-cache

###
GET http://localhost:8200/task/subTasks/1?pageNum=3
Accept: */*
Cache-Control: no-cache

###
GET http://localhost:8200/task/staff/10?pageNum=2
Accept: */*
Cache-Control: no-cache


###
GET http://localhost:8200/task/project/1?pageNum=2
Accept: */*
Cache-Control: no-cache

###
GET http://localhost:8200/task/collection?pageNum=2
Accept: */*
Cache-Control: no-cache

###
GET http://localhost:8200/task/collection/assign/list?pageNum=2
Accept: */*
Cache-Control: no-cache

###
GET http://localhost:8200/task/collection/staff/10?pageNum=1
Accept: */*
Cache-Control: no-cache

###
GET http://localhost:8200/task/contact?pageNum=4
Accept: */*
Cache-Control: no-cache

###
GET http://localhost:8200/task/contact/staff/10?pageNum=2
Accept: */*
Cache-Control: no-cache

###
