###
POST https://flashwallet.tech/api/auth/logout
Accept: */*
Cache-Control: no-cache
Content-Type: application/json



###
POST https://flashwallet.tech/api/auth/sms/code
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "mobile": "918753155642",
  "orgId": 1
}

###
POST https://flashwallet.tech/api/auth/sms/registerAndLogin
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "mobile": "918753155642",
  "code": "359665",
  "orgId": 1
}


###
POST https://flashwallet.tech/api/account/show
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

###
GET https://flashwallet.tech/api/status/all
Accept: */*
Cache-Control: no-cache

###
###
PUT https://flashwallet.tech/api/status/mock
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "trade.loan.loaning": true
}

###




