





###
GET https://flashwallet.tech/api/status/all
Accept: */*
Cache-Control: no-cache



###
GET http://flashwallet.tech/api/status/customer/info
Accept: */*
Cache-Control: no-cache










###
PUT http://flashwallet.tech/api/status/mock
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "customer.info.bank.card": true,
  "customer.info.complete": true,
  "trade.loan.loaning": true
}

###
PUT http://flashwallet.tech/api/status/mock
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "tradeLoanOverdueTimeout": true,
  "customerAuthSuccess": true
}


###
GET http://flashwallet.tech/api/status/show
Accept: */*
Cache-Control: no-cache

###
GET http://flashwallet.tech/api/status/show/step1
Accept: */*
Cache-Control: no-cache

###
GET http://flashwallet.tech/api/status/show/step2
Accept: */*
Cache-Control: no-cache

###




